[package]
name = "Give_me_a_Diamond"
version = "0.1.0"
authors = ["iluadd"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
